version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 12

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db


  db:
    image: amazon/dynamodb-local:latest
    restart: unless-stopped

